name: Publicador Automatico Pinterest

on:
  schedule:
    - cron: '0 9,15,20 * * *'
  workflow_dispatch:

jobs:
  publicar_pin:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install requests pillow google-genai

      - name: Ejecutar bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          PINTEREST_TOKEN: ${{ secrets.PINTEREST_TOKEN }}
          PINTEREST_BOARD_ID: ${{ secrets.PINTEREST_BOARD_ID }}
          AMAZON_TAG: ${{ secrets.AMAZON_TAG }}
        run: python bot.py
