name: Publicador Automático Pinterest

on:
  schedule:
    - cron: '0 9,15,20 * * *'
  workflow_dispatch:

jobs:
  publicar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar librerías
        run: |
          pip install google-genai requests

      - name: Ejecutar Bot Pinterest
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          AMAZON_TAG: ${{ secrets.AMAZON_TAG }}
          PINTEREST_AUTH: ${{ secrets.PINTEREST_AUTH }}
          PINTEREST_CSRF: ${{ secrets.PINTEREST_CSRF }}
        run: python bot.py
