name: Publicador Automático Pinterest

on:
  schedule:
    # 07:00 UTC = 09:00 (España) y 13:00 UTC = 15:00 (España)
    - cron: '0 7,13 * * *'
    # 17:45 UTC = 19:45 (7:45 de la tarde en España)
    - cron: '45 17 * * *'
  workflow_dispatch:

jobs:
  publicar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar librerías
        run: |
          pip install requests google-genai beautifulsoup4

      - name: Ejecutar Bot Pinterest
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          AMAZON_TAG: ${{ secrets.AMAZON_TAG }}
          PINTEREST_AUTH: ${{ secrets.PINTEREST_AUTH }}
          PINTEREST_CSRF: ${{ secrets.PINTEREST_CSRF }}
        run: python bot.py
